### ISSUE TITLE
Revoked certificate to docs.pwabuilder.com

### ISSUE THREAD

**Issue by PedFastTech** [pwa-builder/pwabuilder-MacOS#27]
Trying to visit https://docs.pwabuilder.com/jekyll/update/2018/02/03/how-to-package-mac.html but I cannot because the certificate to docs.pwabuilder.com is revoked.  Also is there any chance in future that PWABuilder.com will have the UI to  build the MacOS PWA apps?

**Comment by JudahGabriel** [comment]
docs.pwabuilder.com are outdated and not particularly useful any more, as our platforms have changed.

As for MacOS and iOS, we're actively investigating enabling this. The reason we took our MacOS platform down was because it used some dated technology that prevented such apps from being accepted by the app store.

**Comment by PedFastTech** [comment]
Hi - please consider enabling this.  I will happily be a guinea pig to get this working.
